name: pull_and_push

on:
  workflow_dispatch:

env:
  SOURCE_IMAGE: "ghcr.io/goauthentik/server"
  TARGET_IMAGE: "docker.io/${{ vars.DOCKERHUB_USERNAME }}/authentik-server"
  IMAGE_VERSION: "2024.10.2"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull "$SOURCE_IMAGE:$IMAGE_VERSION"

      - name: Tag image
        run: docker image tag "$SOURCE_IMAGE:$IMAGE_VERSION" "$TARGET_IMAGE:$IMAGE_VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker image push "$TARGET_IMAGE:$IMAGE_VERSION"
